SELECT  t1.ORDER_NO
       ,t1.MODEL_ID
       ,t1.MODEL_NAME
       ,t1.SELLING_UNIT_PRICE
       ,t1.ITEM_CHARACTER_GROUP_R3_CHARACTER_SERIES_CD
       ,t1.AUTO_RETENTION_COND_MASTER_CATEGORY_NO
       ,t1.MODEL_CATEGORY_MASTER_CATEGORY_NO_KBN
       ,t1.ITEM_MASTER_ITEM_CD
       ,t1.PRODUCT_TYPE
       ,t2.ORDER_NO               AS 'RELATED_ORDER_NO'
       ,t2.MODEL_ID               AS 'RELATED_MODEL_ID'
       ,t2.CATEGORY_NO            AS 'RELATED_CATEGORY_NO'
       ,t2.CATEGORY_NO_KBN        AS 'RELATED_CATEGORY_NO_KBN'
       ,t2.ITEM_CD                AS 'RELATED_ITEM_CD'
       ,t2.R3_CHARACTER_SERIES_CD AS 'RELATED_R3_CHARACTER_SERIES_CD'
FROM
(
	SELECT  ORDER_NO
	       ,MODEL_ID
	       ,MODEL_NAME
	       ,SELLING_UNIT_PRICE
	       ,ITEM_CHARACTER_GROUP_R3_CHARACTER_SERIES_CD
	       ,AUTO_RETENTION_COND_MASTER_CATEGORY_NO
	       ,MODEL_CATEGORY_MASTER_CATEGORY_NO_KBN
	       ,ITEM_MASTER_ITEM_CD
	       ,PRODUCT_TYPE
	FROM c514000640.[【改修】03_SENDABLE_PRODUCTS] with (nolock)
	WHERE LEN(AUTO_RETENTION_COND_MASTER_CATEGORY_NO) = 4 
) t1
INNER JOIN c514000640.[【改修】04_RELATED_PRODUCTS_01_3] t2 with (nolock)/* 「ITEM_CHARACTER_GROUP」の「R3_CHARACTER_SERIES_CD」に、新着/締切商品抽出の際に取得した「ITEM_CHARACTER_GROUP」の「R3_CHARACTER_SERIES_CD」で絞込 */
ON t1.ITEM_CHARACTER_GROUP_R3_CHARACTER_SERIES_CD = t2.R3_CHARACTER_SERIES_CD /* 「MODEL_CATEGORY_MASTER」の「CATEGORY_NO」に、新着/締切商品抽出の際に取得した「AUTO_RETENTION_COND_MASTER」の「CATEGORY_NO」で絞込 */ /* ⇒新着/締切商品の親カテゴリNo(長さが4)であれば子カテゴリNoにも一致とする */ AND t2.CATEGORY_NO LIKE t1.AUTO_RETENTION_COND_MASTER_CATEGORY_NO + '%' /* 「MODEL_CATEGORY_MASTER」の「CATEGORY_NO_KBN」に、新着/締切商品抽出の際に取得した「MODEL_CATEGORY_MASTER」の「CATEGORY_NO_KBN」で絞込(商品抽出の際に区分を'M'で指定しているため抽出された区分も'M') */ AND t1.MODEL_CATEGORY_MASTER_CATEGORY_NO_KBN = t2.CATEGORY_NO_KBN /* 「ITEM_MASTER」の「ITEM_CD」に、新着/締切商品抽出の際に取得した「ITEM_MASTER」の「ITEM_CD」で合致しないこと */ AND t1.ITEM_MASTER_ITEM_CD <> t2.ITEM_CD /* 「ORDER_NO_MASTER」の「MODEL_ID」に、新着/締切商品抽出の際に取得した「ORDER_NO_MASTER」の「MODEL_ID」で合致しないこと */ 
AND t1.MODEL_ID <> t2.MODEL_ID